[project]
name = "meu-projeto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jjpxt", email = "jotajunior.peixoto@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
meu-projeto = "meu_projeto:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
